[project]
name = "python-fullstack-projects"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.11"
dependencies = []

[tool.uv.workspace]
members = [
    "01. Text to Morse Code Converter",
]
