[project]
name = "02-disappearing-text-writing-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.11"
dependencies = [
    "nicegui>=3.7.1",
]
