[project]
name = "01-text-to-morse-code-converter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.11"
dependencies = [
    "numpy>=2.4.2",
]
